name = "MultiBeamCalculator"
uuid = "a8b5cac8-97a3-4729-89b4-5e5d4f751bee"
version = "0.1.0"
authors = ["Angel Rodriguez-Fernandez <rodrigfa@xfel.eu>", "James Wrigley <james.wrigley@xfel.eu>"]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CUDA = "5"
FFTW = "1"
KernelAbstractions = "0.9"
LinearAlgebra = "1"
ProgressMeter = "1"
Statistics = "1"
StatsBase = "0.34.7"
